
app:
  miroBaseUrl: https://miro.com
  miroApiBaseUrl: https://api.miro.com
  # https://miro.com/marketplace/jira/
  clientId: 3074457346182612612
  clientSecret: ""

server:
  port: 3333
  forward-headers-strategy: FRAMEWORK
server.servlet:
  session.timeout: 168h
  session.persistent: true

spring.jackson:
  serialization:
    indent-output: true

spring.mvc:
  log-request-details: true

spring.datasource:
  url: jdbc:h2:file:./miro-plantuml_h2;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
  driver-class-name: org.h2.Driver

spring.h2.console:
  enabled: true
  path: /h2-console
  settings:
    web-admin-password: password
    web-allow-others: false

management.server:
  port: 8088
management.endpoints.web:
  exposure.include: "*"
  base-path: /manage

